apiVersion : apps/v1
kind: Deployment
metadata:
  name: ramya321 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ramya321
  template:
    metadata:
      labels:
        app: ramya321 
    spec:
      containers:
        - name: ramya321 
          image: acrregistry195.azurecr.io/ramyaazuredevops:latest
          ports:
          - containerPort: 8080
