apiVersion: v1
kind: Service
metadata:
    name: bathiniarundotnetarun
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetport: 5000
    selector:
        app: bathiniarundotnetarun
